import { genkit } from 'genkit';
import fs from 'fs';
import { ApolloClient, gql, HttpLink, InMemoryCache } from "@apollo/client/core/index.js"; // Import directly from core
import { googleAI, gemini25FlashPreview0417} from '@genkit-ai/googleai';
import { startFlowServer, expressHandler } from '@genkit-ai/express';

import express from 'express';
import dotenv from 'dotenv';
dotenv.config();
import { z } from 'zod';
import { jwtDecode } from "jwt-decode";

const _googleAI = googleAI({ apiKey: process.env.GOOGLE_API_KEY });
const ai = genkit({
    plugins: [_googleAI],
    promptDir: './llm_prompts',
    model: gemini25FlashPreview0417,
    enableTracingAndMetrics: true 
});

const graphql_endpoint = process.env.GRAPHQL_URL;
const apolloClient = new ApolloClient({
    link: new HttpLink({ 
        uri: graphql_endpoint, 
        fetch,
        // headers: { 
        //     'Authorization': `Bearer ${access_token}` // Pass the extracted toke
        // }   
        }),
        cache: new InMemoryCache(),
});

export const executeGraphQL = ai.defineTool({
        name: "executedGraphQL",
        description: "execute any GraphQL query generated by LLM",
        // inputSchema: z.string(),
    }, 
    async (input, { context }) => {

        console.log(`Input: ${input.query} Context: ${JSON.stringify(context)}`);

        try {

            if( input.query ) {
                const gqlQuery = gql`
                    ${input.query}
                `;

                const graphql_result = await apolloClient.query({
                    query: gqlQuery,
                    headers : {
                        Authorization: `Bearer ${context.access_token}`
                    }
                });
            }

            // return graphql_result.data;

            return "Sample data"
        } catch(error) {
            return `GraphQL query "${input}" execution failed. Error: ${error.message}`
        }     
    }  
);

export const toolsFlow = ai.defineFlow(
    {
        name: "ToolsFlow",
        inputSchema: z.string(),
        // outputSchema: z.string(),
    },
    async (flowInput, {context}) => {
        const prompt = ai.prompt('graphql_agent'); // '.prompt' extension will be added automatically

        const schemaSDL = fs.readFileSync('./llm_prompts/schema.graphql', 'utf-8');

        const generateOptions = {
            system: `
                You are a helpful assistant that understand the following GraphQL schema and provide the information about the public events defined in this schema.
                Schema:
                ${schemaSDL}

                You must help the user generate GraphQL queries based on this schema. Answer only with the stringified query, omit other text.
                `,
            prompt:  "Generate the GraphQL query based on the provided schema and the user input, and pass the generated query to the function 'executedGraphQL'",
            // schema: z.string(), // or use structured if you're returning parsed data
            tools: [executeGraphQL],
        }

        // generate a response
        const llmResponse =  await ai.generate(
            generateOptions,
            context
        );

        const toolRequests = llmResponse.toolRequests;

        if( toolRequests.length == 0 ) {
            console.log("No tool requests found in LLM esponse.");
            return llmResponse;
        }

        const gqlQuery = gql`
            ${llmResponse.query}
        `;

        const graphql_result = await apolloClient.query({
            query: gqlQuery,
        });

        return llmResponse;
    }
);

const port = process.env.PORT ? Number(process.env.PORT) : undefined;

const app = express();
app.use(express.json());

app.post('/toolsFlow', async(req, res) => {
    const headers = req.headers;
    const access_token = headers?.authorization?.split(' ')[1];
    const decoded = jwtDecode(access_token);
    const userId = decoded["signInNames.citizenId"];
    const result = await toolsFlow(req.body.data, {
                                context: { 
                                    headers,
                                    access_token,
                                    userId
                                } 
                            }
                    );
    res.json(result);
})

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});


// startFlowServer({
//     flows: [toolsFlow],
//     port: port,
// });